name: pharmacy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path: ^1.8.3
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  path_provider: ^2.0.15

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.2
  firebase_ui_firestore: ^1.5.4

  provider: ^6.0.5
  email_validator: ^2.1.17
  flutter_svg: ^2.0.7
  mobile_scanner: ^3.3.0
  flutter_local_notifications: ^15.0.0
  just_audio: ^0.9.34
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0

  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  flutter_lints: ^2.0.2

  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/mp3/
