name: pharmacy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  shared_preferences: ^2.1.2

  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  firebase_ui_firestore: ^1.5.3

  provider: ^6.0.5
  email_validator: ^2.1.17
  flutter_svg: ^2.0.7
  mobile_scanner: ^3.2.0
  flutter_local_notifications: ^14.1.1
  just_audio: ^0.9.34

  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  flutter_lints: ^2.0.1

  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
