name: pharmacy
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.1.2

  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  cloud_firestore: ^4.8.0
  firebase_ui_firestore: ^1.5.2

  provider: ^6.0.5
  email_validator: ^2.1.17
  flutter_svg: ^2.0.6

  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  flutter_lints: ^2.0.1

  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
